<<<<<<< HEAD
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import type { Metadata, Viewport } from 'next';
import { Space_Grotesk, DM_Mono } from 'next/font/google';
import './globals.css';

/* ── Fuente Display: Space Grotesk (distintiva, geométrica, moderna) ── */
const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

/* ── Fuente Mono: DM Mono (para subtítulos y badges técnicos) ── */
const dmMono = DM_Mono({
  variable: '--font-dm-mono',
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  style: ['normal', 'italic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Home | Mi App',
  description: 'Página principal del sistema — Fullstack TypeScript + Next.js + Vercel',
  keywords: ['TypeScript', 'Next.js', 'Vercel', 'Fullstack', 'React'],
  authors: [{ name: 'SETP Team' }],
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
>>>>>>> b1058892a1eb56935e5d29983ff4aee157d20888
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
<<<<<<< HEAD
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
=======
      lang="es"
      className={`${spaceGrotesk.variable} ${dmMono.variable}`}
    >
      <body>{children}</body>
>>>>>>> b1058892a1eb56935e5d29983ff4aee157d20888
    </html>
  );
}
